using PX.Archiver;
using PX.Common;
using PX.Common.Collection;
using PX.Common.Cryptography;
using PX.Common.Encoders;
using PX.Common.Extensions;
using PX.Common.IO;
using PX.Common.Mail;
using PX.Common.MIME;
using PX.Common.Parser;
using PX.Common.Serialization;
using PX.Common.Service;
using PX.Common.Services;
using PX.Data;
using PX.Data.RelativeDates;
using PX.Web.UI;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

[assembly: Extension]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: AllowPartiallyTrustedCallers]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: InternalsVisibleTo("PX.Api.Shared")]
[assembly: InternalsVisibleTo("PX.Api.TSBasedScreen")]
[assembly: InternalsVisibleTo("PX.Api.TSBasedScreen.Tests")]
[assembly: InternalsVisibleTo("PX.Export")]
[assembly: InternalsVisibleTo("PX.Data")]
[assembly: InternalsVisibleTo("PX.Data.AspNetCore")]
[assembly: InternalsVisibleTo("PX.Api.OData")]
[assembly: InternalsVisibleTo("PX.Api.OData.GI.Legacy")]
[assembly: InternalsVisibleTo("PX.Owin")]
[assembly: InternalsVisibleTo("Unit.Tests")]
[assembly: InternalsVisibleTo("PX.Common.Tests")]
[assembly: InternalsVisibleTo("PX.Data.Tests")]
[assembly: InternalsVisibleTo("PX.Data.GI.TestFramework")]
[assembly: InternalsVisibleTo("PX.BusinessProcess.Tests")]
[assembly: InternalsVisibleTo("PX.Reports")]
[assembly: InternalsVisibleTo("PX.LicensePolicy")]
[assembly: InternalsVisibleTo("PX.Telemetry")]
[assembly: InternalsVisibleTo("PX.Tests.AspNetCore.TestHost")]
[assembly: InternalsVisibleTo("PX.Tests.Unit")]
[assembly: InternalsVisibleTo("PX.Api.ContractBased")]
[assembly: InternalsVisibleTo("PX.Api.ContractBased.Tests")]
[assembly: InternalsVisibleTo("PX.Api.Mobile.Tests")]
[assembly: InternalsVisibleTo("PX.Api.Mobile")]
[assembly: InternalsVisibleTo("PX.OidcClient")]
[assembly: InternalsVisibleTo("PX.ResourceGovernor")]
[assembly: InternalsVisibleTo("PX.Web.Site")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("PX.Web.Customization")]
[assembly: InternalsVisibleTo("PX.Web.UI")]
[assembly: InternalsVisibleTo("PX.Web.UI.Frameset")]
[assembly: InternalsVisibleTo("PX.Web.UI.Frameset.WebApi")]
[assembly: InternalsVisibleTo("PX.Distributed.Tests")]
[assembly: Guid("082eacd7-3ecc-4fe3-bfbf-a3e12b629b61")]
[assembly: AssemblyCompany("PX.Common")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("Copyright © 2005-2025 Acumatica, Inc. All rights reserved.")]
[assembly: AssemblyFileVersion("25.193.0171")]
[assembly: AssemblyInformationalVersion("25.193.0171")]
[assembly: AssemblyProduct("PX.Common")]
[assembly: AssemblyTitle("PX.Common")]
[assembly: SuppressIldasm]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: TypeForwardedTo(typeof (ZipArchiveWrapper))]
[assembly: TypeForwardedTo(typeof (Array<>))]
[assembly: TypeForwardedTo(typeof (ArrayComparer))]
[assembly: TypeForwardedTo(typeof (ArrayComparer<>))]
[assembly: TypeForwardedTo(typeof (DList<,>))]
[assembly: TypeForwardedTo(typeof (KList<,>))]
[assembly: TypeForwardedTo(typeof (Lookup<,>))]
[assembly: TypeForwardedTo(typeof (ReadOnlyBiDictionary<,>))]
[assembly: TypeForwardedTo(typeof (ReadOnlyBiDictionaryExt))]
[assembly: TypeForwardedTo(typeof (Rect))]
[assembly: TypeForwardedTo(typeof (RTree))]
[assembly: TypeForwardedTo(typeof (Set<>))]
[assembly: TypeForwardedTo(typeof (TwoWayLookup<,>))]
[assembly: TypeForwardedTo(typeof (WeakSet<>))]
[assembly: TypeForwardedTo(typeof (Composite))]
[assembly: TypeForwardedTo(typeof (ConcurrentDictionaryExtensions))]
[assembly: TypeForwardedTo(typeof (CryptoProvider))]
[assembly: TypeForwardedTo(typeof (RSACryptoProvider))]
[assembly: TypeForwardedTo(typeof (SymmetricCryptoProvider))]
[assembly: TypeForwardedTo(typeof (DateTimeExtensions))]
[assembly: TypeForwardedTo(typeof (Drawing))]
[assembly: TypeForwardedTo(typeof (RawEncoding))]
[assembly: TypeForwardedTo(typeof (UnicodeEncoding))]
[assembly: TypeForwardedTo(typeof (EnumerableExtensions))]
[assembly: TypeForwardedTo(typeof (EventArgs<>))]
[assembly: TypeForwardedTo(typeof (ExceptionExtensions))]
[assembly: TypeForwardedTo(typeof (ExceptionExtensions.RethrowResult<>))]
[assembly: TypeForwardedTo(typeof (AdjustmentRuleExtensions))]
[assembly: TypeForwardedTo(typeof (StringExtensions))]
[assembly: TypeForwardedTo(typeof (FontFamilyEx))]
[assembly: TypeForwardedTo(typeof (FormatHelper<>))]
[assembly: TypeForwardedTo(typeof (GCHelper))]
[assembly: TypeForwardedTo(typeof (PX.Common.GS1.Parser))]
[assembly: TypeForwardedTo(typeof (GUID))]
[assembly: TypeForwardedTo(typeof (IgnoreXmlSurrogateAttribute))]
[assembly: TypeForwardedTo(typeof (IMap<,>))]
[assembly: TypeForwardedTo(typeof (FilenameValidator))]
[assembly: TypeForwardedTo(typeof (IReadOnlySet<>))]
[assembly: TypeForwardedTo(typeof (ITypeArrayOf<>))]
[assembly: TypeForwardedTo(typeof (Lazy))]
[assembly: TypeForwardedTo(typeof (Localizer))]
[assembly: TypeForwardedTo(typeof (ConnectionSettings))]
[assembly: TypeForwardedTo(typeof (CredentialSettings))]
[assembly: TypeForwardedTo(typeof (Email))]
[assembly: TypeForwardedTo(typeof (EmailParser))]
[assembly: TypeForwardedTo(typeof (Mailbox))]
[assembly: TypeForwardedTo(typeof (SecurityProtocolType))]
[assembly: TypeForwardedTo(typeof (MainTools))]
[assembly: TypeForwardedTo(typeof (Map<,>))]
[assembly: TypeForwardedTo(typeof (Mask))]
[assembly: TypeForwardedTo(typeof (MemProfilerTypeInfo))]
[assembly: TypeForwardedTo(typeof (MediaTypes))]
[assembly: TypeForwardedTo(typeof (MediaTypes.Application))]
[assembly: TypeForwardedTo(typeof (MediaTypes.Image))]
[assembly: TypeForwardedTo(typeof (MediaTypes.Text))]
[assembly: TypeForwardedTo(typeof (MediaTypes.Multipart))]
[assembly: TypeForwardedTo(typeof (MediaTypes.Message))]
[assembly: TypeForwardedTo(typeof (MsgNotLocalizable))]
[assembly: TypeForwardedTo(typeof (MultiValueDictionary<,>))]
[assembly: TypeForwardedTo(typeof (Net_Utils))]
[assembly: TypeForwardedTo(typeof (NonComparedAttribute))]
[assembly: TypeForwardedTo(typeof (NonGenericIDictionaryExtensions))]
[assembly: TypeForwardedTo(typeof (NonGenericIEnumerableExtensions))]
[assembly: TypeForwardedTo(typeof (NullableDictionary<,>))]
[assembly: TypeForwardedTo(typeof (NullableExtensions))]
[assembly: TypeForwardedTo(typeof (OrderedHashSet<>))]
[assembly: TypeForwardedTo(typeof (OrderedHashSet<>.ReadOnlyOrderedHashSet))]
[assembly: TypeForwardedTo(typeof (OrdinalStringTupleComparer))]
[assembly: TypeForwardedTo(typeof (ParseException))]
[assembly: TypeForwardedTo(typeof (AggregateNode))]
[assembly: TypeForwardedTo(typeof (BinaryOpNode))]
[assembly: TypeForwardedTo(typeof (ConstantNode))]
[assembly: TypeForwardedTo(typeof (DataType))]
[assembly: TypeForwardedTo(typeof (Delimiters))]
[assembly: TypeForwardedTo(typeof (ExpressionException))]
[assembly: TypeForwardedTo(typeof (ExpressionLocalizer))]
[assembly: TypeForwardedTo(typeof (ExpressionNode))]
[assembly: TypeForwardedTo(typeof (ExpressionNode.ConvertMethod))]
[assembly: TypeForwardedTo(typeof (FunctionContext))]
[assembly: TypeForwardedTo(typeof (FunctionNode))]
[assembly: TypeForwardedTo(typeof (INodeVisitor<>))]
[assembly: TypeForwardedTo(typeof (INodeVisitorExt<>))]
[assembly: TypeForwardedTo(typeof (IRelativeDateNode))]
[assembly: TypeForwardedTo(typeof (Lexer))]
[assembly: TypeForwardedTo(typeof (LikeNode))]
[assembly: TypeForwardedTo(typeof (Messages))]
[assembly: TypeForwardedTo(typeof (NameNode))]
[assembly: TypeForwardedTo(typeof (Operator))]
[assembly: TypeForwardedTo(typeof (Operator.CallbackFunc))]
[assembly: TypeForwardedTo(typeof (ParserException))]
[assembly: TypeForwardedTo(typeof (ParserTypeHelper))]
[assembly: TypeForwardedTo(typeof (Token))]
[assembly: TypeForwardedTo(typeof (UnaryOpNode))]
[assembly: TypeForwardedTo(typeof (ValueType))]
[assembly: TypeForwardedTo(typeof (ZeroOpNode))]
[assembly: TypeForwardedTo(typeof (PreEnumeratedEnumerable<>))]
[assembly: TypeForwardedTo(typeof (PXCommonLocalizer))]
[assembly: TypeForwardedTo(typeof (PXInternalUseOnlyAttribute))]
[assembly: TypeForwardedTo(typeof (PXKeyedCollection<,>))]
[assembly: TypeForwardedTo(typeof (PXLocalizableAttribute))]
[assembly: TypeForwardedTo(typeof (PXLocalizeCaller))]
[assembly: TypeForwardedTo(typeof (PXLocalizeFormatCaller))]
[assembly: TypeForwardedTo(typeof (PXLocalizeMessageCaller))]
[assembly: TypeForwardedTo(typeof (PXPath))]
[assembly: TypeForwardedTo(typeof (IPXWeakCollection))]
[assembly: TypeForwardedTo(typeof (PXHashCode))]
[assembly: TypeForwardedTo(typeof (PXSerializableAttribute))]
[assembly: TypeForwardedTo(typeof (SerializationTypeProxyAttribute))]
[assembly: TypeForwardedTo(typeof (IVersionService))]
[assembly: TypeForwardedTo(typeof (Version))]
[assembly: TypeForwardedTo(typeof (ServiceLocatorExtensions))]
[assembly: TypeForwardedTo(typeof (ILicenseService))]
[assembly: TypeForwardedTo(typeof (Sign))]
[assembly: TypeForwardedTo(typeof (Str))]
[assembly: TypeForwardedTo(typeof (StringStream))]
[assembly: TypeForwardedTo(typeof (TextUtils))]
[assembly: TypeForwardedTo(typeof (Trie))]
[assembly: TypeForwardedTo(typeof (TypeArray))]
[assembly: TypeForwardedTo(typeof (TypeArray.IsNotEmpty))]
[assembly: TypeForwardedTo(typeof (TypeArray.IArrayConcat))]
[assembly: TypeForwardedTo(typeof (TypeArray.IArrayConcat<>))]
[assembly: TypeForwardedTo(typeof (TypeArray.IArrayConcat<,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.Concat<,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.Append<,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.Prepend<,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.Empty))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.IFilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeArrayOf<>.FilledWith<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>))]
[assembly: TypeForwardedTo(typeof (TypeHelper))]
[assembly: TypeForwardedTo(typeof (TypeLoaderExtensions))]
[assembly: TypeForwardedTo(typeof (ITodayUtc))]
[assembly: TypeForwardedTo(typeof (DateValue))]
[assembly: TypeForwardedTo(typeof (FinancialPeriodManagerStub))]
[assembly: TypeForwardedTo(typeof (InfixParser))]
[assembly: TypeForwardedTo(typeof (MonthEnd))]
[assembly: TypeForwardedTo(typeof (MonthStart))]
[assembly: TypeForwardedTo(typeof (NumberValue))]
[assembly: TypeForwardedTo(typeof (QuarterEnd))]
[assembly: TypeForwardedTo(typeof (QuarterStart))]
[assembly: TypeForwardedTo(typeof (RPNCalculator))]
[assembly: TypeForwardedTo(typeof (ShuntingYardParser))]
[assembly: TypeForwardedTo(typeof (Today))]
[assembly: TypeForwardedTo(typeof (TodayUTC))]
[assembly: TypeForwardedTo(typeof (Token))]
[assembly: TypeForwardedTo(typeof (WeekEnd))]
[assembly: TypeForwardedTo(typeof (WeekStart))]
[assembly: TypeForwardedTo(typeof (YearEnd))]
[assembly: TypeForwardedTo(typeof (YearStart))]
[assembly: TypeForwardedTo(typeof (RelativeDatesManager))]
[assembly: TypeForwardedTo(typeof (PXIcons))]
[assembly: TypeForwardedTo(typeof (Sprite))]
[assembly: TypeForwardedTo(typeof (Sprite.Main))]
[assembly: TypeForwardedTo(typeof (Sprite.Control))]
[assembly: TypeForwardedTo(typeof (Sprite.Tree))]
[assembly: TypeForwardedTo(typeof (Sprite.Text))]
[assembly: TypeForwardedTo(typeof (Sprite.Ac))]
[assembly: TypeForwardedTo(typeof (JoinToDictionary))]
