// Decompiled with JetBrains decompiler
// Type: PX.Data.PXDBOperation
// Assembly: PX.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 2A82D21C-DAFC-4371-ACE9-BAD417AC5A62
// Assembly location: D:\tmp\2025 R2 DLLs\PX.Data.dll
// XML documentation location: D:\tmp\2025 R2 DLLs\PX.Data.xml

using System;

#nullable disable
namespace PX.Data;

/// <summary>This enumeration specifies the type of a T-SQL statement generated by the Acumatica Data Access Layer.
/// The enumeration is used to indicate the type of the operation and the option set for the operation.
/// <code>PXDBOperation</code> supports the <code>FlagsAttribute</code> attribute, which allows <code>PXDBOperation</code> members to be represented as bit fields in the enumeration value.
/// </summary>
/// <example>
/// <code title="Example" lang="CS">
/// //Getting the type of an operation
/// protected virtual void DACName_FieldName_CommandPreparing(
///     PXCache sender, PXCommandPreparingEventArgs e)
/// {
///     PXDBOperation operationKind = e.Operation &amp; PXDBOperation.Command;
/// }</code>
/// <code title="Example2" groupname="Example" lang="CS">
/// //Getting the option set for an operation
/// protected virtual void DACName_FieldName_CommandPreparing(
///     PXCache sender,
///     PXCommandPreparingEventArgs e)
/// {
///     PXDBOperation operationOptions = e.Operation &amp; PXDBOperation.Option;
/// }</code>
/// </example>
[Flags]
public enum PXDBOperation
{
  /// <summary>The SELECT statement.</summary>
  Select = 0,
  /// <summary>The UPDATE statement.</summary>
  Update = 1,
  /// <summary>The INSERT statement.</summary>
  Insert = 2,
  /// <summary>The DELETE statement.</summary>
  Delete = Insert | Update, // 0x00000003
  /// <exclude />
  Command = Delete, // 0x00000003
  /// <summary>The operation has no options set.</summary>
  Normal = 0,
  /// <summary>Specifies an aggregate operation.</summary>
  GroupBy = 4,
  /// <summary>The result of the operation cannot be used to prepare
  /// the external representation.</summary>
  Internal = 8,
  /// <summary>The operation contains a sorting, filter, or search query across
  /// any DAC field visible in the UI.</summary>
  External = 16, // 0x00000010
  /// <summary>The operation is changing the system data visibility and transferring
  /// it from the system data segment to the customer data segment.</summary>
  Second = 32, // 0x00000020
  /// <exclude />
  ReadOnly = 64, // 0x00000040
  /// <summary>The operation is select in massdataexport scenario and subselect for field required</summary>
  SubselectForExport = ReadOnly | External, // 0x00000050
  /// <exclude />
  Option = SubselectForExport | Second | Internal | GroupBy, // 0x0000007C
  /// <summary>The operation is in the SELECT statement.</summary>
  SelectClause = 128, // 0x00000080
  /// <summary>The operation is in the WHERE clause.</summary>
  WhereClause = 256, // 0x00000100
  /// <summary>The operation is in the ORDER BY clause.</summary>
  OrderByClause = 512, // 0x00000200
  /// <summary>The operation is in the GROUP BY clause.</summary>
  GroupByClause = 1024, // 0x00000400
  /// <summary>The operation is in a nested SELECT statement.</summary>
  NestedSelectInReport = 2048, // 0x00000800
  /// <exclude />
  Place = NestedSelectInReport | GroupByClause | OrderByClause | WhereClause | SelectClause, // 0x00000F80
  /// <exclude />
  ReadItem = 4096, // 0x00001000
}
