// Decompiled with JetBrains decompiler
// Type: PX.Data.PXUIType
// Assembly: PX.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 2A82D21C-DAFC-4371-ACE9-BAD417AC5A62
// Assembly location: D:\tmp\2025 R2 DLLs\PX.Data.dll
// XML documentation location: D:\tmp\2025 R2 DLLs\PX.Data.xml

#nullable disable
namespace PX.Data;

public static class PXUIType
{
  /// <summary>
  /// Legacy UI (if URL is relative: ~/...) / External URL (if URL is absolute: https://...).
  /// </summary>
  public const string LegacyUI = "E";
  /// <summary>
  /// New UI screen, based on TypeScript. URL is autogenerated: $"~/Scripts/Screens/{tenantId}/{screenId}.html", old URL is stored in DB.
  /// </summary>
  public const string NewUIScreen = "T";
  public const string Default = "D";
}
