// Decompiled with JetBrains decompiler
// Type: PX.Objects.PM.ProjectWipAdjustmentEntry_Workflow
// Assembly: PX.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: CF76B6BF-0C8A-413D-8225-C21BEAE6CEEC
// Assembly location: D:\tmp\2025 R2 DLLs\PX.Objects.dll
// XML documentation location: D:\tmp\2025 R2 DLLs\PX.Objects.xml

using PX.Data;
using PX.Data.WorkflowAPI;
using System;
using System.Linq.Expressions;

#nullable disable
namespace PX.Objects.PM;

public class ProjectWipAdjustmentEntry_Workflow : PXGraphExtension<ProjectWipAdjustmentEntry>
{
  public virtual void Configure(PXScreenConfiguration config)
  {
    ProjectWipAdjustmentEntry_Workflow.Configure(config.GetScreenConfigurationContext<ProjectWipAdjustmentEntry, PMWipAdjustment>());
  }

  protected static void Configure(
    WorkflowContext<ProjectWipAdjustmentEntry, PMWipAdjustment> context)
  {
    BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured processingCategory = context.Categories.CreateNew("Processing", (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IAllowOptionalConfigCategory, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured>) (category => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured) category.DisplayName("Processing")));
    BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured correctionCategory = context.Categories.CreateNew("Corrections", (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IAllowOptionalConfigCategory, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured>) (category => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured) category.DisplayName("Corrections")));
    BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured printingAndEmail = context.Categories.CreateNew("Printing and Emailing", (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IAllowOptionalConfigCategory, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured>) (category => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured) category.DisplayName("Printing and Emailing")));
    BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured otherCategory = context.Categories.CreateNew("OtherCategory", (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IAllowOptionalConfigCategory, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured>) (category => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IConfigured) category.DisplayName("Other")));
    context.AddScreenConfigurationFor((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ScreenConfiguration.IStartConfigScreen, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ScreenConfiguration.IConfigured>) (screen => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ScreenConfiguration.IConfigured) ((BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ScreenConfiguration.INeedStateIDScreen) screen).StateIdentifierIs<PMWipAdjustment.status>().AddDefaultFlow((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Workflow.INeedStatesFlow, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Workflow.IConfigured>) (flow => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Workflow.IConfigured) flow.WithFlowStates((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IContainerFillerStates>) (fss =>
    {
      fss.Add<ProjectWipAdjustmentStatus.onHold>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.FlowState.INeedAnyFlowStateConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured>) (flowState => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured) ((BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.FlowState.INeedAnyFlowStateConfig) flowState.IsInitial()).WithActions((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IContainerFillerActions>) (actions =>
      {
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.removeHold), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured) c.IsDuplicatedInToolbar().WithConnotation((ActionConnotation) 3)));
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.addProjects), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured) c.IsDuplicatedInToolbar()));
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.refreshLines), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured) c.IsDuplicatedInToolbar()));
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipReport), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipAdjustment), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
      }))));
      fss.Add<ProjectWipAdjustmentStatus.open>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.FlowState.INeedAnyFlowStateConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured>) (flowState => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured) flowState.WithActions((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IContainerFillerActions>) (actions =>
      {
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.hold), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.release), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured) c.IsDuplicatedInToolbar().WithConnotation((ActionConnotation) 3)));
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipReport), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipAdjustment), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
      }))));
      fss.Add<ProjectWipAdjustmentStatus.released>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.FlowState.INeedAnyFlowStateConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured>) (flowState => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.BaseFlowStep.IConfigured) flowState.WithActions((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IContainerFillerActions>) (actions =>
      {
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.reverse), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured) c.IsDuplicatedInToolbar().WithConnotation((ActionConnotation) 0)));
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipReport), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
        actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipAdjustment), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IAllowOptionalConfig, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionState.IConfigured>) null);
      }))));
    })).WithTransitions((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IContainerFillerTransitions>) (transitions =>
    {
      transitions.AddGroupFrom<ProjectWipAdjustmentStatus.onHold>((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.ISourceContainerFillerTransitions>) (ts => ts.Add((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.INeedTarget, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured>) (t => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured) t.To<ProjectWipAdjustmentStatus.open>().IsTriggeredOn((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.removeHold))))));
      transitions.AddGroupFrom<ProjectWipAdjustmentStatus.open>((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.ISourceContainerFillerTransitions>) (ts =>
      {
        ts.Add((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.INeedTarget, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured>) (t => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured) t.To<ProjectWipAdjustmentStatus.onHold>().IsTriggeredOn((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.hold))));
        ts.Add((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.INeedTarget, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured>) (t => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured) t.To<ProjectWipAdjustmentStatus.released>().IsTriggeredOn((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.release))));
      }));
      transitions.AddGroupFrom<ProjectWipAdjustmentStatus.released>((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.ISourceContainerFillerTransitions>) (ts => ts.Add((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.INeedTarget, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured>) (t => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Transition.IConfigured) t.To<ProjectWipAdjustmentStatus.onHold>().IsTriggeredOn((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.reverse))))));
    })))).WithActions((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IContainerFillerActions>) (actions =>
    {
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.addProjects), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(otherCategory)));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.refreshLines), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(otherCategory)));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.removeHold), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(processingCategory).WithFieldAssignments((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IContainerFillerFields>) (fa => fa.Add<PMWipAdjustment.hold>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) false)))))));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.hold), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(processingCategory).WithFieldAssignments((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IContainerFillerFields>) (fa => fa.Add<PMWipAdjustment.hold>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) true)))))));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.release), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(processingCategory).WithFieldAssignments((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IContainerFillerFields>) (fa =>
      {
        fa.Add<PMWipAdjustment.hold>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) false)));
        fa.Add<PMWipAdjustment.released>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) true)));
      }))));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipReport), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(printingAndEmail)));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.printWipAdjustment), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(printingAndEmail)));
      actions.Add((Expression<Func<ProjectWipAdjustmentEntry, PXAction<PMWipAdjustment>>>) (g => g.reverse), (Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IAllowOptionalConfigAction, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured>) (c => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionDefinition.IConfigured) c.WithCategory(correctionCategory).WithFieldAssignments((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IContainerFillerFields>) (fa =>
      {
        fa.Add<PMWipAdjustment.hold>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) true)));
        fa.Add<PMWipAdjustment.released>((Func<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.INeedRightOperand, BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured>) (f => (BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.Assignment.IConfigured) f.SetFromValue((object) false)));
      }))));
    })).WithCategories((Action<BoundedTo<ProjectWipAdjustmentEntry, PMWipAdjustment>.ActionCategory.IContainerFillerCategories>) (categories =>
    {
      categories.Add(processingCategory);
      categories.Add(otherCategory);
    }))));
  }
}
