// Decompiled with JetBrains decompiler
// Type: PX.Objects.SO.SOShipmentStatus
// Assembly: PX.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: CF76B6BF-0C8A-413D-8225-C21BEAE6CEEC
// Assembly location: D:\tmp\2025 R2 DLLs\PX.Objects.dll
// XML documentation location: D:\tmp\2025 R2 DLLs\PX.Objects.xml

using PX.Data;
using PX.Data.BQL;

#nullable enable
namespace PX.Objects.SO;

public class SOShipmentStatus
{
  public const 
  #nullable disable
  string Open = "N";
  public const string Hold = "H";
  public const string Completed = "C";
  public const string Cancelled = "L";
  public const string Confirmed = "F";
  public const string Invoiced = "I";
  public const string Receipted = "R";
  public const string AutoGenerated = "A";
  public const string PartiallyInvoiced = "Y";

  public class ListAttribute : PXStringListAttribute
  {
    public static readonly (string, string)[] ValuesToLabels = new (string, string)[9]
    {
      ("N", "Open"),
      ("H", "On Hold"),
      ("C", "Completed"),
      ("L", "Canceled"),
      ("F", "Confirmed"),
      ("I", "Invoiced"),
      ("Y", "Partially Invoiced"),
      ("R", "Receipted"),
      ("A", "Auto-Generated")
    };

    public ListAttribute()
      : base(SOShipmentStatus.ListAttribute.ValuesToLabels)
    {
    }
  }

  public class open : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.open>
  {
    public open()
      : base("N")
    {
    }
  }

  public class hold : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.hold>
  {
    public hold()
      : base("H")
    {
    }
  }

  public class completed : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.completed>
  {
    public completed()
      : base("C")
    {
    }
  }

  public class cancelled : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.cancelled>
  {
    public cancelled()
      : base("L")
    {
    }
  }

  public class confirmed : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.confirmed>
  {
    public confirmed()
      : base("F")
    {
    }
  }

  public class invoiced : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.invoiced>
  {
    public invoiced()
      : base("I")
    {
    }
  }

  public class partiallyInvoiced : 
    BqlType<
    #nullable enable
    IBqlString, string>.Constant<
    #nullable disable
    SOShipmentStatus.partiallyInvoiced>
  {
    public partiallyInvoiced()
      : base("Y")
    {
    }
  }

  public class receipted : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.receipted>
  {
    public receipted()
      : base("R")
    {
    }
  }

  public class autoGenerated : BqlType<
  #nullable enable
  IBqlString, string>.Constant<
  #nullable disable
  SOShipmentStatus.autoGenerated>
  {
    public autoGenerated()
      : base("A")
    {
    }
  }
}
