using PX.SM;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

[assembly: Extension]
[assembly: Obfuscation(Feature = "debug", Exclude = false)]
[assembly: Obfuscation(Feature = "apply to type * when serializable: renaming", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "string encryption", Exclude = true)]
[assembly: Obfuscation(Feature = "apply to type * when delegate: renaming", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type * when has-attribute('JetBrains.Annotations.UsedImplicitlyAttribute'): renaming", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.BQL.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.*Database*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.*PXAccess*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Wiki.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Maintenance.GI.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.CepReporting.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Description.GI.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Handlers.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Translation.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Local*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.EP.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.EP.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.RichTextEdit.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Search.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Services.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.MassProcess.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.TM.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: Obfuscation(Feature = "apply to type PX.Data.Automation.*: all", Exclude = true, ApplyToMembers = true)]
[assembly: AllowPartiallyTrustedCallers]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: InternalsVisibleTo("PX.AIStudio")]
[assembly: InternalsVisibleTo("PX.Web.UI")]
[assembly: InternalsVisibleTo("Customization")]
[assembly: InternalsVisibleTo("PX.Web.Customization")]
[assembly: InternalsVisibleTo("PX.Web.UI.Design")]
[assembly: InternalsVisibleTo("PX.DataSync")]
[assembly: InternalsVisibleTo("PX.DataSync.Core")]
[assembly: InternalsVisibleTo("PX.MySql")]
[assembly: InternalsVisibleTo("PX.Api.OData")]
[assembly: InternalsVisibleTo("PX.Api.OData.GI.Legacy")]
[assembly: InternalsVisibleTo("PX.Olap")]
[assembly: InternalsVisibleTo("PX.Data.BQL.Fluent")]
[assembly: InternalsVisibleTo("PX.Api.ContractBased")]
[assembly: InternalsVisibleTo("PX.Api.ContractBased.Tests")]
[assembly: InternalsVisibleTo("PX.PushNotifications")]
[assembly: InternalsVisibleTo("PX.BusinessProcess")]
[assembly: InternalsVisibleTo("PX.Dashboards")]
[assembly: InternalsVisibleTo("PX.Dashboards.Controls")]
[assembly: InternalsVisibleTo("PX.Dashboards.Widgets")]
[assembly: InternalsVisibleTo("PX.Web.UI.Frameset")]
[assembly: InternalsVisibleTo("PX.Web.UI.Frameset.Tests")]
[assembly: InternalsVisibleTo("PX.Wiki.Render.Markdown")]
[assembly: InternalsVisibleTo("Unit.Tests")]
[assembly: InternalsVisibleTo("PX.Tests.Common")]
[assembly: InternalsVisibleTo("PX.Common.Tests")]
[assembly: InternalsVisibleTo("PX.SiteMap")]
[assembly: InternalsVisibleTo("PX.Data.Tests")]
[assembly: InternalsVisibleTo("PX.Data.ServiceLocatorFree.Tests")]
[assembly: InternalsVisibleTo("PX.Export.Tests")]
[assembly: InternalsVisibleTo("PX.LicensePolicy.Tests")]
[assembly: InternalsVisibleTo("PX.Hosting.Tests")]
[assembly: InternalsVisibleTo("PX.Data.ReferentialIntegrity.Tests")]
[assembly: InternalsVisibleTo("PX.Api.Shared.Tests")]
[assembly: InternalsVisibleTo("PX.Data.GI.TestFramework")]
[assembly: InternalsVisibleTo("PX.Data.GI.Tests.DbDependent")]
[assembly: InternalsVisibleTo("PX.BusinessProcess.Tests")]
[assembly: InternalsVisibleTo("PX.LicensePolicy")]
[assembly: InternalsVisibleTo("BQL.Tests")]
[assembly: InternalsVisibleTo("PX.SmsProvider.UI")]
[assembly: InternalsVisibleTo("PX.Commerce.Core")]
[assembly: InternalsVisibleTo("PX.Api.Webhooks")]
[assembly: InternalsVisibleTo("PX.Logging.Tests")]
[assembly: InternalsVisibleTo("PX.Api.OData.v4")]
[assembly: InternalsVisibleTo("PX.Api.OData.v4.Tests")]
[assembly: InternalsVisibleTo("PX.Api.Shared")]
[assembly: InternalsVisibleTo("PX.OidcClient")]
[assembly: InternalsVisibleTo("PX.OidcClient.Tests")]
[assembly: InternalsVisibleTo("PX.Tests.Unit")]
[assembly: InternalsVisibleTo("PX.Data.AspNetCore")]
[assembly: InternalsVisibleTo("PX.PgSql")]
[assembly: InternalsVisibleTo("PX.Web.UI.Frameset.WebApi")]
[assembly: InternalsVisibleTo("PX.ScreenPreferences")]
[assembly: InternalsVisibleTo("PX.Api.TSBasedScreen")]
[assembly: InternalsVisibleTo("PX.Api.TSBasedScreen.Tests")]
[assembly: InternalsVisibleTo("PX.Telemetry")]
[assembly: InternalsVisibleTo("PX.Telemetry.SerilogSink")]
[assembly: InternalsVisibleTo("PX.ResourceGovernor")]
[assembly: InternalsVisibleTo("PX.Owin")]
[assembly: InternalsVisibleTo("PX.Web.Site")]
[assembly: InternalsVisibleTo("PX.OAuthClient")]
[assembly: InternalsVisibleTo("PX.Api.Mobile.Tests")]
[assembly: InternalsVisibleTo("PX.ML.Common")]
[assembly: InternalsVisibleTo("PX.ML.CrossSales")]
[assembly: InternalsVisibleTo("PX.ML.GI")]
[assembly: InternalsVisibleTo("PX.Data.GI.Benchmarks")]
[assembly: InternalsVisibleTo("PX.Api.Mobile")]
[assembly: InternalsVisibleTo("PX.Api.ReportDesigner")]
[assembly: InternalsVisibleTo("PX.Api.Web")]
[assembly: InternalsVisibleTo("PX.Web.ScreenToModernUIConverter")]
[assembly: InternalsVisibleTo("PX.GI.QueryLanguage")]
[assembly: InternalsVisibleTo("PX.GI.QueryLanguage.Tests")]
[assembly: InternalsVisibleTo("PX.GI.QueryLanguage.Server")]
[assembly: InternalsVisibleTo("PX.Tests.Stubs.Data")]
[assembly: InternalsVisibleTo("PX.Tests.AspNetCore.TestHost")]
[assembly: InternalsVisibleTo("PX.DacSchemaBrowser.Tests")]
[assembly: InternalsVisibleTo("PX.Distributed")]
[assembly: InternalsVisibleTo("PX.Distributed.Tests")]
[assembly: InternalsVisibleTo("PX.CloudServices")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("16b9ebb2-91db-4fdb-ab02-acfe07298059")]
[assembly: PXBlobStorageProvider(typeof (PXBlobStorageFileProvider), "Local File Folder")]
[assembly: PXBlobStorageProvider(typeof (PXBlobStorageAzureProvider), "Azure Blob Storage")]
[assembly: PXBlobStorageProvider(typeof (PXBlobStorageS3Provider), "Amazon S3 Storage")]
[assembly: AssemblyCompany("PX.Data")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("Copyright © 2005-2025 Acumatica, Inc. All rights reserved.")]
[assembly: AssemblyFileVersion("25.193.0171")]
[assembly: AssemblyInformationalVersion("25.193.0171")]
[assembly: AssemblyProduct("PX.Data")]
[assembly: AssemblyTitle("PX.Data")]
[assembly: AssemblyVersion("1.0.0.0")]
